export const projects = [
  {
    title: 'Andalucía Turismo',
    description: "Este sitio web es un blog turístico sobre Andalucía alojada en una instancia Linux S3 en AWS. Creado con GraphCMS, un Sistema de Gestión de Contenidos dedicado que facilita la creación de contenido; categorías, artículos completos en markdown, información del autor, comentarios y mucho más... ",
      image: '/images/blog-andalucia.jpg',
      tags: ['NextJs', 'GraphQl', 'Tailwind CSS'],
    source: 'https://github.com/manuetov/turiblog_next_graphcms',
    visit: 'https://www.andaluciaturismo.es/',
    id: 0,
  },
  {
    title: 'Nefluxkix',
    description:"App que muestra un catálogo de películas dinámicamente mediante la consulta a la API Movie Database y mediante otra API de Youtube se pueden reproducir los trailers de las peliculas mostradas o las que se buscan en el buscador de la aplicación. Responsive con React-Bootstrap. Desplegado en Netlify",
    image: '/images/netfluxkix.jpg',
    tags: ['React', 'React-Bootstrap', 'JavaScript'],
    source: 'https://github.com/manuetov/movie-video-react',
    visit: 'https://movie-video-trailer.netlify.app/',
    id: 1,
  },
  {
    title: 'Play-Lyrics',
    description: "App que reproduce la música procedente de la consulta a una API con funciones de búsqueda, letras, exploración de canciones, listas de éxitos, populares y mucho más. Completamente responsive con Tailwind CSS. Desplegado en Netlify",
      image: '/images/lyriks.jpg',
      tags: ['React', 'Redux', 'Tailwind CSS'],
    source: 'https://github.com/manuetov/spotilyrics-react-shazamApi',
    visit: 'https://shazam-lyriks.netlify.app/',
    id: 2,
  },
  {
    title: 'ParodiaSeo',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Fashion',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Espacios Vivos',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/espaciosvivos.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Recetas Mediterraneas',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/recetasmedite.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Web de Seo',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/webdseo.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'Fittness con Salud',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/fitness.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'Espacios Vivos',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 9,
  },
  {
    title: 'Info Crypto News',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/infocrypto.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 10,
  },

];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];