export const projects = [
  {
    title: 'Andalucía Turismo',
    description: "Using React, NextJs, GraphQl. Este sitio web es un blog de turismo",
      image: '/images/andturismo.jpg',
      tags: ['NextJs', 'React', 'GraphQl'],
    source: 'https://github.com/manuetov/turiblog_next_graphcms',
    visit: 'https://www.andaluciaturismo.es/',
    id: 0,
  },
  {
    title: 'Nefluxkix',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/netfluxkix.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/manuetov/movie-video-react',
    visit: 'https://movie-video-trailer.netlify.app/',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/lyriks.jpg',
      tags: ['React', 'TailWind'],
    source: 'https://github.com/manuetov/spotilyrics-react-shazamApi',
    visit: 'https://shazam-lyriks.netlify.app/',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];